apiVersion: v1
kind: Service
metadata:
  name: altibase-exporter
  labels:
    app: altibase-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9399"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9399
      targetPort: http
      protocol: TCP
  selector:
    app: altibase-exporter
